# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20180622_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hireDate',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
